# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b7ba9b704b244ec22efa506838cbda6d270755bef2afaae8cd059f38967e27bc5ffdc18d4e12c0fa8818323cbb834f63209fb01acc06437a8e8fe4bcccda137

test:
  secret_key_base: 75f609d894cce0976527ccfe8e3ba7aa3a710f5de8ac136a6aeebddeea2e7248acf0bbf5d1fc61e626c2c0b5f3dc9b4c4fafc0f8d3147f98d186e24b54b3108a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
